import HelloWorld from "@/components/helloworld";
import Head from "next/head";



export default function Home() {
  return (
    <>
      <Head>
        <title>Meu primeiro site em React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Ola, mundo! meu primeiro site em React</h1>
      {/*commentario em JSX*/}
      {/* Importando o componente HelloWorld */} 
     <HelloWorld />
     <HelloWorld />

    </>
  );
}
