import Contador from "@/components/Contador";
import Helloworld from "@/components/helloworld";
import User from "@/components/User";
import Info from "@/components/Info";
import Head from "next/head";
import InfoBotao from "../components/InfoBotao"; 



export default function Home() {
  return (
    <>
      <Head>
        <title>Meu Primeiro Site em React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Olá, Mundo! Meu Primeiro Site em React</h1>
      {/*commentario em JSX*/}
      {/* Importando o componente HelloWorld */} 
     <Helloworld />
    <User />
    <Info />
    <br />
    <Contador />
    <InfoBotao />
    </>
  );
}
